### ISSUE TITLE
기획

### ISSUE THREAD

**Issue by akalswl14** [akalswl14/checkme#1]
- 어떤 기능을 만들건지
- 어떤 화면을 만들건지
- 디자인 초안
- 패키징 툴 정하기
- 브랜치 만들것
- 깃허브 활용하기

계획해서 6/28 18:00까지 plan 폴더에 plan_minji이렇게 저장하기, 마크다운으로

- [x] 시은

- [x] 은아

- [x] 민지

**Comment by aeuna** [comment]
all complete!!!
